image: gitpod/workspace-full

tasks:
  - before: |
      echo "Compilation..."
      mkdir -p out
      javac -d out src/entites/*.java
    init: |
      echo "Lancement de l'application"
      java -cp out entites.Main

# expose le port 8080 pour ttyd
ports:
  - port: 8080
    onOpen: open-preview
